### ISSUE TITLE
Specify a Week and Players sub-resource for get_teams_roster

### ISSUE THREAD

**Issue by peacing** [josuebrunel/yahoo-fantasy-sport#24]

**Comment by peacing** [comment]
So I created this issue, then changed to code to fix it and wanted to commit the changes by doing the following:

![screen shot 2015-07-02 at 8 14 55 pm](https://cloud.githubusercontent.com/assets/11055355/8490447/183dd6c0-20f7-11e5-84b1-e12b375c959f.png)

Was this correct? Should I now close this issue?

**Comment by josuebrunel** [comment]
Hello Paul. 

> Was this correct? Should I now close this issue?

Yes it was.

**But** since i merged your **pull request** and i **might have** changed some code (sometimes no need to), the first thing to do, is to **update your forked repository**. To do so , follow the steps below : 

**Main page of the forked repository**
![paul-forked-repo-1](https://cloud.githubusercontent.com/assets/1620640/8492525/48c56a2a-214b-11e5-99e6-cabe5858258a.png)

**Switch bases**
![paul-forked-repo-2](https://cloud.githubusercontent.com/assets/1620640/8492526/48c5f846-214b-11e5-9335-49e1501680e0.png)

**Create a pull request on your forked repository then merge it**
![paul-forked-repo-3](https://cloud.githubusercontent.com/assets/1620640/8492527/48ca510c-214b-11e5-8385-a00445fb791c.png)

**Finally**

``` shell
$ git pull origin master
```

## Note :

Since your already have committed beforing pulling, you might have some **merge conflict** when doing the pull.

If you have trouble with some merge conflict, let me know.

Have a good day

**Comment by peacing** [comment]
I'm happy to report the merge went relatively smoothly without and conflicts ;)

**Comment by josuebrunel** [comment]
Oh great, happy to hear that
